<?php
/**
 * Settings screen diagnostics.
 *
 * @package Faytuks\StructuredData
 */

declare( strict_types=1 );

namespace Faytuks\StructuredData\Admin;

use Faytuks\StructuredData\PostMeta\ArticleType;
use Faytuks\StructuredData\Schema\NewsroomPolicies;
use Faytuks\StructuredData\Schema\OrganizationTransformer;
use Faytuks\StructuredData\Schema\RankMathIntegration;
use Faytuks\StructuredData\Settings\SettingsRepository;
use Faytuks\StructuredData\Support\RankMath;
use Faytuks\StructuredData\Updater;

/**
 * Read-only status panel plus a preview of the organization entity.
 *
 * Nothing here exposes tokens or other credentials: the update section reports
 * only whether a token is configured.
 */
final class Diagnostics {

	/**
	 * Settings repository.
	 *
	 * @var SettingsRepository
	 */
	private $settings;

	/**
	 * Rank Math integration.
	 *
	 * @var RankMathIntegration
	 */
	private $integration;

	/**
	 * Per-post article type control.
	 *
	 * @var ArticleType
	 */
	private $article_type;

	/**
	 * Constructor.
	 *
	 * @param SettingsRepository  $settings     Settings repository.
	 * @param RankMathIntegration $integration  Rank Math integration.
	 * @param ArticleType         $article_type Per-post article type control.
	 */
	public function __construct( SettingsRepository $settings, RankMathIntegration $integration, ArticleType $article_type ) {
		$this->settings     = $settings;
		$this->integration  = $integration;
		$this->article_type = $article_type;
	}

	/**
	 * Render the diagnostics panel.
	 *
	 * @return void
	 */
	public function render(): void {
		if ( ! current_user_can( Settings::CAPABILITY ) ) {
			return;
		}

		?>
		<h2><?php esc_html_e( 'Diagnostics', 'fn-structured-data' ); ?></h2>
		<table class="widefat striped fn-structured-data-diagnostics">
			<tbody>
			<?php foreach ( $this->rows() as $label => $value ) : ?>
				<tr>
					<th scope="row"><?php echo esc_html( $label ); ?></th>
					<td><?php echo esc_html( $value ); ?></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>

		<h3><?php esc_html_e( 'Organization entity preview', 'fn-structured-data' ); ?></h3>
		<p class="description">
			<?php esc_html_e( 'Preview of the publisher entity this plugin would produce, based on the values Rank Math currently supplies plus the overrides above. The live graph is generated by Rank Math on each request; this is not stored anywhere.', 'fn-structured-data' ); ?>
		</p>
		<pre class="fn-structured-data-preview"><code><?php echo esc_html( $this->preview() ); ?></code></pre>
		<?php
	}

	/**
	 * The diagnostics rows.
	 *
	 * @return array<string, string>
	 */
	private function rows(): array {
		$yes = __( 'Yes', 'fn-structured-data' );
		$no  = __( 'No', 'fn-structured-data' );

		$rank_math_version = RankMath::version();

		$rows = array(
			__( 'Plugin version', 'fn-structured-data' ) => FN_STRUCTURED_DATA_VERSION,
			__( 'Rank Math detected', 'fn-structured-data' ) => RankMath::is_active() ? $yes : $no,
			__( 'Rank Math version', 'fn-structured-data' ) => '' !== $rank_math_version ? $rank_math_version : __( 'Not discoverable', 'fn-structured-data' ),
			__( 'Rank Math Pro detected', 'fn-structured-data' ) => RankMath::is_pro_active() ? $yes : $no,
			__( 'Rank Math schema module active', 'fn-structured-data' ) => RankMath::is_schema_module_active() ? $yes : $no,
			__( 'Schema integration active', 'fn-structured-data' ) => $this->integration->is_available() ? $yes : $no,
			__( 'JSON-LD filter priority', 'fn-structured-data' ) => (string) RankMathIntegration::FILTER_PRIORITY,
			__( 'Configured organization type', 'fn-structured-data' ) => OrganizationTransformer::TARGET_TYPE,
			__( 'Newsroom policy fields configured', 'fn-structured-data' ) => sprintf(
				/* translators: 1: configured count, 2: total available count. */
				__( '%1$d of %2$d', 'fn-structured-data' ),
				$this->settings->configured_policy_count(),
				count( NewsroomPolicies::setting_keys() )
			),
			__( 'Article type control on', 'fn-structured-data' ) => implode( ', ', $this->article_type->post_types() ),
			__( 'Update checker active', 'fn-structured-data' ) => Updater::is_active() ? $yes : $no,
			__( 'Update source', 'fn-structured-data' )  => Updater::repository_url(),
			__( 'Update release channel', 'fn-structured-data' ) => Updater::RELEASE_BRANCH,
			__( 'Update token configured', 'fn-structured-data' ) => Updater::has_token() ? $yes : $no,
		);

		return $rows;
	}

	/**
	 * The organization entity this plugin would emit, as pretty JSON.
	 *
	 * @return string
	 */
	private function preview(): string {
		$transformer = new OrganizationTransformer();
		$entity      = $transformer->transform( $this->baseline_publisher(), $this->settings->get() );

		$json = wp_json_encode( $entity, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE );

		return is_string( $json ) ? $json : '';
	}

	/**
	 * A stand-in for Rank Math's publisher entity.
	 *
	 * Built from the values Rank Math is configured with so the preview matches
	 * the live graph as closely as possible without rendering the frontend.
	 *
	 * @return array<string, mixed>
	 */
	private function baseline_publisher(): array {
		$inherited = RankMath::inherited_organization();

		$publisher = array(
			'@type' => 'Organization',
			'@id'   => home_url( '/' ) . '#organization',
			'name'  => '' !== $inherited['name'] ? $inherited['name'] : get_bloginfo( 'name' ),
			'url'   => '' !== $inherited['url'] ? $inherited['url'] : home_url( '/' ),
		);

		if ( '' !== $inherited['logo'] ) {
			$publisher['logo'] = array(
				'@type' => 'ImageObject',
				'@id'   => home_url( '/' ) . '#logo',
				'url'   => $inherited['logo'],
			);
		}

		if ( '' !== $inherited['email'] ) {
			$publisher['email'] = $inherited['email'];
		}

		if ( '' !== $inherited['telephone'] ) {
			$publisher['telephone'] = $inherited['telephone'];
		}

		return $publisher;
	}
}
